server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bryanjesuscastro2003/billService
          default-label: version1
          search-paths: config-cloud
